import MainLayout from '@/layout/MainLayout'
import './globals.css'

import { Montserrat } from 'next/font/google'
export const dynamic = 'force-dynamic'
const montserrat = Montserrat({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainLayout elem={children} />
      </body>
    </html>
  )
}
